[
  { name: "Athletics", icon: "Testing" },
  { name: "Badminton", icon: "Testing" },
  { name: "Baseball", icon: "Testing" },
  { name: "Basketball", icon: "Testing" },
  { name: "Bodybuilding", icon: "Testing" },
  { name: "Bowling", icon: "Testing" },
  { name: "Boxing", icon: "Testing" },
  { name: "Chess", icon: "Testing" },
  { name: "Cricket", icon: "Testing" },
  { name: "Cycling", icon: "Testing" },
  { name: "Football", icon: "Testing" },
  { name: "Golf", icon: "Testing" },
  { name: "Gymnastics", icon: "Testing" },
  { name: "Handball", icon: "Testing" },
  { name: "Hockey", icon: "Testing" },
  { name: "Ice Hockey", icon: "Testing" },
  { name: "Judo", icon: "Testing" },
  { name: "Kabaddi", icon: "Testing" },
  { name: "Motor sport", icon: "Testing" },
  { name: "Netball", icon: "Testing" },
  { name: "Polo", icon: "Testing" },
  { name: "Roller Skating", icon: "Testing" },
  { name: "Rowing", icon: "Testing" },
  { name: "Rugby", icon: "Testing" },
  { name: "Sailing", icon: "Testing" },
  { name: "Shooting", icon: "Testing" },
  { name: "Skiing", icon: "Testing" },
  { name: "Snooker", icon: "Testing" },
  { name: "Softball", icon: "Testing" },
  { name: "Squash", icon: "Testing" },
  { name: "Swimming", icon: "Testing" },
  { name: "Table Tennis", icon: "Testing" },
  { name: "Taekwondo", icon: "Testing" },
  { name: "Tennis", icon: "Testing" },
  { name: "Tent pegging", icon: "Testing" },
  { name: "Volleyball", icon: "Testing" },
  { name: "Weightlifting", icon: "Testing" },
  { name: "Wrestling", icon: "Testing" },
  { name: "Wushu", icon: "Testing" },
];
